services:
  # This is an alternative docker-compose configuration that uses bridge networking
  # instead of host networking mode. Use this if you need to communicate with
  # other Docker services but also reach the host's MCP server.
  
  langflow:
    image: langflowai/langflow:latest
    container_name: langflow
    # Use bridge networking (default)
    # network_mode: bridge  # This is the default so we don't need to specify it
    ports:
      # Standard langflow UI port
      - "7860:7860"
      # Forward host's MCP port to the same port inside the container
      # This allows container to access host's MCP server via localhost:8000
      - "127.0.0.1:8000:8000"
    volumes:
      - ./components:/home/user/app/src/components
    environment:
      - LANGFLOW_COMPONENTS_PATH=/home/user/app/src/components/custom/tools
      - LANGFLOW_LOG_LEVEL=DEBUG
      - LANGFLOW_AUTO_RELOAD=true
      - DOCKER_HOST_IP=172.17.0.1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: langflow run --host 0.0.0.0 --port 7860 --backend-only --dev
    restart: unless-stopped
    networks:
      - monitoring

networks:
  monitoring:
    external: true 